import { ObjectID } from 'mongodb';
import { Document } from 'mongoose';

export interface IActivity extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectID;

  name: string;

  candidates: any;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}
