import { ObjectID } from 'mongodb';
import { Document } from 'mongoose';

export interface IMember extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectID;

  email: string;

  idCard: string;

  password: string;

  status: boolean;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}
